services:
  law_firm_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: law_firm_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - WHATSAPP_BOT_URL=http://law_firm_whatsapp_bot:3000
      - FIREBASE_CREDENTIALS=/firebase-key.json
    env_file:
      - .env
    volumes:
      - ./firebase-key.json:/firebase-key.json:ro
    networks:
      - law_firm_network
    depends_on:
      law_firm_whatsapp_bot:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  law_firm_whatsapp_bot:
    build:
      context: .
      dockerfile: Dockerfile.whatsapp
    container_name: law_firm_whatsapp_bot
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FIREBASE_CREDENTIALS=/firebase-key.json
      - FASTAPI_WEBHOOK_URL=http://law_firm_backend:8000/api/v1/whatsapp/webhook
    env_file:
      - .env
    volumes:
      - whatsapp_session:/app/whatsapp_session
      - whatsapp_messages:/app/messages
      - ./firebase-key.json:/firebase-key.json:ro
    networks:
      - law_firm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.15'

  law_firm_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: law_firm_frontend
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - law_firm_network
    depends_on:
      - law_firm_backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

volumes:
  whatsapp_session:
    driver: local
    name: law_firm_whatsapp_session
  whatsapp_messages:
    driver: local
    name: law_firm_whatsapp_messages

networks:
  law_firm_network:
    driver: bridge
    name: law_firm_network
